### ISSUE TITLE
I couldn't do it

### ISSUE THREAD

**Issue by williancs** [hamedb89/enhanced-router#1]
This is my composer.json and when I run 'composer update', it doesn't do anything.
Can you help me?

{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/hamedb89/enhanced-router"
        }
    ],
    "require": {
        "laravel/framework": "4.2.*",
    },
    "autoload": {
        "classmap": [
            "app/commands",
            "app/controllers",
            "app/models",
            "app/database/migrations",
            "app/database/seeds",
            "app/tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ]
    },
    "config": {
        "preferred-install": "dist"
    },
    "minimum-stability": "stable"
}

**Comment by hamedb89** [comment]
Hey,

i think you have a syntax error on line 13. No need for a comma after
`"laravel/framework": "4.2.*"`

did that do the trick?

**Comment by kaoz70** [comment]
I could'nt get this to download either:

```
{
"name": "laravel/laravel",
"description": "The Laravel Framework.",
"keywords": ["framework", "laravel"],
"license": "MIT",
"type": "project",
"require": {
    "laravel/framework": "4.2.*",
    "sammyk/laravel-facebook-sdk": "~1.1",
    "guzzlehttp/guzzle": "5.0.3",
    "barryvdh/laravel-ide-helper": "~1.11",
    "doctrine/dbal": "2.5.*@dev",
    "teepluss/theme": "dev-master",
    "intervention/image": "~2.0"
},
"autoload": {
    "classmap": [
        "app/commands",
        "app/controllers",
        "app/models",
        "app/database/migrations",
        "app/database/seeds",
        "app/tests/TestCase.php"
    ],
    "files": [
        "app/helpers.php"
    ]
},
"repositories": [
    {
        "type": "git",
        "url": "https://github.com/hamedb89/enhanced-router"
    }
],
"scripts": {
    "post-install-cmd": [
        "php artisan clear-compiled",
        "php artisan optimize"
    ],
    "post-update-cmd": [
        "php artisan clear-compiled",
        "php artisan ide-helper:generate",
        "php artisan optimize"
    ],
    "post-create-project-cmd": [
        "php artisan key:generate"
    ]
},
"config": {
    "preferred-install": "dist"
},
"minimum-stability": "stable"
}
```

**Comment by kaoz70** [comment]
OK I was able to download it like:

```
"repositories": [
    {
        "type": "package",
        "package": {
            "name": "enhanced-router",
            "version": "1.0.4",
            "source": {
                "url": "https://github.com/hamedb89/enhanced-router.git",
                "type": "git",
                "reference": "1.0.4"
            }
        }
    }
],

"require": {
    "enhanced-router": "1.0.4"
},
```

But It doesent load the service provider im getting:
    Symfony\Component\Debug\Exception\FatalErrorException thrown with message "Class 'Hamedbahrami\EnhancedRouter\EnhancedRouterServiceProvider' not found"

Stacktrace:
#1 Symfony\Component\Debug\Exception\FatalErrorException in C:\Program Files (x86)\Ampps\www\project1\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php:157
#0 Illuminate\Exception\Handler:handleShutdown in <#unknown>:0

**Comment by hamedb89** [comment]
did you add the service provider to app/config/app.php?

```
'providers' => array(
    ...,
    'Hamedbahrami\EnhancedRouter\EnhancedRouterServiceProvider'
)
```

**Comment by kaoz70** [comment]
Yep, Its there, that was the first place I looked.

**Comment by hamedb89** [comment]
That is a bit odd. From the error message I cannot really tell whats wrong. The error message indicates that the system cannot find the service provider class from the vendor folder.

I would check if the classes are even loaded or can be used in any file by instantiating any class from my repository. If the classes from my repo aren't known in your system, you could say its an autoloading problem.

**Comment by kaoz70** [comment]
Ill try this again in another time, I hard coded some stuff in my routes
for now, which is why I needed this repo, but I really dont have the time
right now to debug this issue. It might just be my project.

Thanks for the time anyway :)

**Comment by tannermccoleman** [comment]
This can be solved by adding the following to your composer.json

```
 "require": {
    "hamedbahrami/enhanced-router": "1.0.*"
}
```
